# Generated by Django 2.1.1 on 2018-09-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneStockShow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='date', max_length=32)),
                ('Open', models.CharField(default='open', max_length=32)),
                ('Close', models.CharField(default='close', max_length=32)),
                ('Low', models.CharField(default='low', max_length=32)),
                ('High', models.CharField(default='high', max_length=32)),
                ('stock_num', models.CharField(default='stock_num', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='stockmodeld',
            name='stock_num',
            field=models.CharField(default='stock_num', max_length=32),
        ),
    ]
