# Generated by Django 2.1.1 on 2018-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneStockShow', '0002_auto_20180909_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodeld',
            name='have_pre',
            field=models.NullBooleanField(default=False),
        ),
    ]
